#!/usr/bin/env python3
"""Catani -> SCET (MS-bar) conversion of the gamma* -> q qbar g helicity
coefficients at one and two loops (3 coloured partons, one colour structure).

With Omega1 = I^(1)(eps) Omega0 + Omega1fin and Catani's two-loop formula
(arXiv:0904.2665 (3.17)-(3.21)), minimal subtraction of the infrared poles
gives at mu^2 = -s123
    C1 = Omega1fin + I1 Omega0,
    C2 = Omega2fin + I1 Omega1fin + X2 Omega0,  X2 = I1^2/2 + R^(0),
I1 = eps^0 coefficient of I^(1)(eps), R(eps) = -(b0/eps) I^(1)(eps)
+ e^{-eps g}Gamma(1-2eps)/Gamma(1-eps) (b0/eps + K) I^(1)(2 eps) + H^(2)(eps).
Logs L_ij = ln(-s_ij/mu^2 - i0). Checked against MCFM 10.3's timelike
schemeconvC0 and schemeconv2lM0 (src/SCET1j/mod_nnlo_z1jet.f90, GPL): equal
(one loop: MCFM's C0; two loop: its M0). Writes x2zero.inc for hard21.f90.
Usage: python3 scheme_conversion.py   (sympy; about a minute)"""
import sympy as sp
e = sp.symbols('epsilon')
CA, CF, NF, TR = sp.symbols('C_A C_F N_F T_R', positive=True)
L12, L13, L23 = sp.symbols('L12 L13 L23')     # L_ij = ln(-s_ij/mu^2)
z2, z3 = sp.zeta(2), sp.zeta(3)
N = CA; invN = CA - 2*CF                       # N -> CA, 1/N -> CA - 2 CF
b0 = (11*CA - 4*TR*NF)/6
K = (sp.Rational(67,18) - sp.pi**2/6)*CA - sp.Rational(10,9)*TR*NF
order = 4
def E(x):   # e^{x gamma}/Gamma(1-x) = exp(-sum_{k>=2} zeta_k x^k/k)
    return sp.exp(-sum(sp.zeta(k)*x**k/k for k in range(2, order+2)))
def I1(x):
    S = lambda L: sp.exp(-x*L)
    return -E(x)/2*(N*(1/x**2 + sp.Rational(3,4)/x + b0/(2*N*x))*(S(L13)+S(L23)) - invN*(1/x**2 + sp.Rational(3,2)/x)*S(L12))
def ser(f, n=1):
    return sp.series(f, e, 0, n).removeO()
I1s = sp.expand(ser(I1(e), 2))
I10 = sp.expand(I1s.coeff(e, 0))
G2 = sp.exp(sum(sp.zeta(k)*(2**k-1)*e**k/k for k in range(2, order+2)))  # e^{-eps gamma}Gamma(1-2eps)/Gamma(1-eps)
R = -(b0/e)*I1(e) + G2*(b0/e + K)*I1(2*e)
R0 = sp.expand(ser(R, 1).coeff(e, 0))
# pole check: R + I1^2/2 - P[I1] I1 + P[I1]^2 must have poles proportional to nothing finite-dependent: just print R's poles count
conv2 = sp.expand(I10**2/2 + R0)
# MCFM's timelike region 2a (s12 > 0, s13, s23 < 0, mu^2 = s45 > 0): their logs in terms of ours
i = sp.I; pi = sp.pi
lg12, lg13, lg23 = sp.symbols('lg12 lg13 lg23')   # Log(s45/s12), Log(-s45/s13), Log(-s45/s23)
sub = {L12: -lg12 - i*pi, L13: -lg13, L23: -lg23}
C0 = (18*CA*i*pi - 36*CF*i*pi + CA*pi**2 + 2*CF*pi**2 + 6*CA*i**2*pi**2 - 12*CF*i**2*pi**2 +
      6*(CA - 2*CF)*(3 + 2*i*pi)*lg12 + 6*(CA - 2*CF)*lg12**2 + (-20*CA + 4*NF*TR)*lg13 - 6*CA*lg13**2 -
      20*CA*lg23 + 4*NF*TR*lg23 - 6*CA*lg23**2)/24
M0 = (-2*(CA*(-67 + 3*pi**2) + 20*NF*TR)*(72*CA*i*pi - 144*CF*i*pi + CA*pi**2 + 2*CF*pi**2 + 24*CA*i**2*pi**2 -
      48*CF*i**2*pi**2 + 24*(CA - 2*CF)*(3 + 2*i*pi)*lg12 + 24*(CA - 2*CF)*lg12**2 + (-80*CA + 16*NF*TR)*lg13 -
      24*CA*lg13**2 - 80*CA*lg23 + 16*NF*TR*lg23 - 24*CA*lg23**2) +
      3*(18*CA*i*pi - 36*CF*i*pi + CA*pi**2 + 2*CF*pi**2 + 6*CA*i**2*pi**2 - 12*CF*i**2*pi**2 +
      6*(CA - 2*CF)*(3 + 2*i*pi)*lg12 + 6*(CA - 2*CF)*lg12**2 + (-20*CA + 4*NF*TR)*lg13 - 6*CA*lg13**2 -
      20*CA*lg23 + 4*NF*TR*lg23 - 6*CA*lg23**2)**2
      - 2*(11*CA - 4*NF*TR)*(11*CA*pi**2 + 18*CF*pi**2 - 108*CA*i**2*pi**2 + 216*CF*i**2*pi**2 - 6*CA*i*pi**3 +
      12*CF*i*pi**3 - 24*CA*i**3*pi**3 + 48*CF*i**3*pi**3 - 4*NF*pi**2*TR + 36*CA*z3 + 72*CF*z3 -
      6*(CA - 2*CF)*pi*(36*i + pi + 12*i**2*pi)*lg12 - 36*(CA - 2*CF)*(3 + 2*i*pi)*lg12**2 - 24*(CA - 2*CF)*lg12**3 +
      6*CA*pi**2*lg13 + 24*(5*CA - NF*TR)*lg13**2 + 24*CA*lg13**3 + 6*CA*pi**2*lg23 + 120*CA*lg23**2 -
      24*NF*TR*lg23**2 + 24*CA*lg23**3))/3456
# MCFM: alpha1 (as/4pi) = Catani + C0, i.e. in as/2pi: 2*C0 ; two loop: 4*M0
d1 = sp.simplify(sp.expand(I10.subs(sub) - C0))
d2 = sp.simplify(sp.expand(conv2.subs(sub) - M0))
assert d2 == 0, d2
print('two loop: equal to MCFM schemeconv2lM0')
assert d1 == 0, d1
print('one loop: equal to MCFM schemeconvC0')


from sympy.printing.fortran import fcode
num = {CA: 3, CF: sp.Rational(4, 3), TR: sp.Rational(1, 2)}
X = sp.expand(sp.expand(I10**2/2 + R0).subs(num)).subs(sp.zeta(3), sp.Symbol('zeta3'))
open('x2zero.inc', 'w').write('! generated by scheme_conversion.py (N = 3, T_R = 1/2)\n'
    + fcode(sp.N(X, 20), standard=2003, source_format='free', assign_to='r') + '\n')
print('I1 =', sp.expand(I10.subs(num)))
print('wrote x2zero.inc')
