######################################################################
# Makefile.inc for proVBFH-inclusive 
# File generated with:
#  ./configure
######################################################################

# external programs needed
LHEXEC=lhapdf-config
#HPEXEC=hoppet-config
HPEXEC=/home/karlberg/tools/hoppet/hoppet-config
# general settings 
FF=gfortran
