"""FORM program for l q(p1) -> l q(p2) g(p3) g(p4) (see gen.py)."""
from gen import amp
NAV = "D34*(d_(a3,a4)*(p4(s1)-p3(s1)) - d_(a4,s1)*(p3(a3)+2*p4(a3)) + d_(s1,a3)*(2*p3(a4)+p4(a4)))"
A1 = [("1", [("g","a3"),("S",[(1,"p2"),(1,"p3")],"D23"),("g","a4"),("S",[(1,"p2"),(1,"p3"),(1,"p4")],"D234"),("g","mu")]),
      ("1", [("g","a3"),("S",[(1,"p2"),(1,"p3")],"D23"),("g","mu"),("S",[(1,"p1"),(-1,"p4")],"D14"),("g","a4")]),
      ("1", [("g","mu"),("S",[(1,"p1"),(-1,"p3"),(-1,"p4")],"D134"),("g","a3"),("S",[(1,"p1"),(-1,"p4")],"D14"),("g","a4")]),
      (NAV, [("g","s1"),("S",[(1,"p2"),(1,"p3"),(1,"p4")],"D234"),("g","mu")]),
      (NAV, [("g","mu"),("S",[(1,"p1"),(-1,"p3"),(-1,"p4")],"D134"),("g","s1")])]
A2 = [("1", [("g","a4"),("S",[(1,"p2"),(1,"p4")],"D24"),("g","a3"),("S",[(1,"p2"),(1,"p3"),(1,"p4")],"D234"),("g","mu")]),
      ("1", [("g","a4"),("S",[(1,"p2"),(1,"p4")],"D24"),("g","mu"),("S",[(1,"p1"),(-1,"p3")],"D13"),("g","a3")]),
      ("1", [("g","mu"),("S",[(1,"p1"),(-1,"p3"),(-1,"p4")],"D134"),("g","a4"),("S",[(1,"p1"),(-1,"p3")],"D13"),("g","a3")]),
      ("-"+NAV, [("g","s1"),("S",[(1,"p2"),(1,"p3"),(1,"p4")],"D234"),("g","mu")]),
      ("-"+NAV, [("g","mu"),("S",[(1,"p1"),(-1,"p3"),(-1,"p4")],"D134"),("g","s1")])]
POL = ("(-d_(a3,b3)+(p3(a3)*p4(b3)+p4(a3)*p3(b3))*i34)"
       "*(-d_(a4,b4)+(p4(a4)*p3(b4)+p3(a4)*p4(b4))*i34)")
HEL = [("77", 7, 7), ("76", 7, 6), ("66", 6, 6)]
out = ["* generated by gen_qgg.py: l q(p1) -> l q(p2) g(p3) g(p4)",
       "Vectors k,kp,p1,p2,p3,p4;", "Indices mu,nu,a3,b3,a4,b4,s1,s2;",
       "Symbols D23,D24,D234,D14,D13,D134,D34,i34;"]
amps = {"1": A1, "2": A2}
for tag, l, h in HEL:
    for X in "12":
        for Y in "12":
            out.append(f"Local T{X}{Y}h{tag} = (1/2)*g_(1,kp)*g_(1,mu)*g{l}_(1)*g_(1,k)*g_(1,nu)"
                       f"\n * (1/2)*g_(2,p2)*(\n {amp(amps[X], 2)}\n )*g{h}_(2)*g_(2,p1)*(\n {amp(amps[Y], 2, conj=True)}\n ) * {POL};")
out += ["trace4,1;", "trace4,2;", ".sort",
        "id kp = k + p1 - p2 - p3 - p4;",
        "id k.k = 0; id p1.p1 = 0; id p2.p2 = 0; id p3.p3 = 0; id p4.p4 = 0;",
        ".sort"]
for tag, _, _ in HEL:
    out.append(f"Local X1h{tag} = T11h{tag} + T22h{tag};")
    out.append(f"Local X2h{tag} = T12h{tag} + T21h{tag};")
out += [".sort", "Drop " + ",".join(f"T{X}{Y}h{t}" for t, _, _ in HEL for X in "12" for Y in "12") + ";",
        "Format 255;", "Format nospaces;", "Print;", ".end"]
open("qgg.frm", "w").write("\n".join(out) + "\n")
