#!/usr/bin/env python3
"""Regenerate src/disent_o2_trees.f: FORM programs (gen_o2.py, gen_prod.py)
-> optimised Fortran (prod/*.f) -> subroutines (wrap.py). Needs `form`."""
import os, subprocess, sys
import gen_o2 as g, gen_prod as gp, wrap
os.makedirs("prod", exist_ok=True)
H = g.HELS
S4 = {"qa": [(1,"p2")], "qb": [(-1,"p1")], "qc": [(1,"p3")], "qd": [(1,"p4")]}
jobs = {
 "qgg3": (g.qgg({"qa": [(1,"p2")], "qb": [(-1,"p1")], "pc": [(1,"p3")], "pd": [(1,"p4")]}, "-1", H),
          {"X1PV": "X1h77 - X1h76", "X2PV": "X2h77 - X2h76", "X1SY": "X1h77 + X1h76", "X2SY": "X2h77 + X2h76"}, False),
 "d13": (g.fourq_line1(S4, "-1", H), {"DPV": "Dh77 - Dh76", "DSY": "Dh77 + Dh76"}, False),
 "e3": (g.fourq_exch(S4, "-1", H), {"EPV": "Eh77 - Eh76", "ESY": "Eh77 + Eh76"}, False),
 "exx3": (g.fourq_exch(S4, "-1", H, attach=("xx",)), {"EXXPV": "Eh77 - Eh76", "EXXSY": "Eh77 + Eh76"}, False),
 "exy3": (g.fourq_exch(S4, "-1", H, attach=("xy",)), {"EXYPV": "Eh77 - Eh76", "EXYSY": "Eh77 + Eh76"}, False),
 "conthr3": (g.conthr({"qa": [(1,"p2")], "qb": [(-1,"p1")], "pc": [(1,"p3")]}, "-1", H),
             {"C3PV": "Ch77 - Ch76", "C3SY": "Ch77 + Ch76"}, True),
}
for name, (body, ex, vv) in jobs.items():
    open(f"prod/{name}.frm", "w").write(gp.production(body, ex, f"{name}.f", "", "", "", vv=vv))
    if os.path.exists(f"prod/{name}.f"): os.remove(f"prod/{name}.f")
    subprocess.run(["form", "-q", f"{name}.frm"], cwd="prod", check=True, stdout=subprocess.DEVNULL)
M4 = ["k","p1","p2","p3","p4"]
E_DENS = {"Dcd": [(1,"p3"),(1,"p4")], "Dab": [(1,"p2"),(-1,"p1")], "Dx1": [(1,"p2"),(1,"p3"),(1,"p4")],
          "Dx2": [(-1,"p1"),(1,"p3"),(1,"p4")], "Dx3": [(1,"p3"),(1,"p2"),(-1,"p1")], "Dx4": [(1,"p4"),(1,"p2"),(-1,"p1")],
          "Dcab": [(1,"p3"),(1,"p2"),(1,"p4")], "Dx1b": [(-1,"p1"),(1,"p2"),(1,"p4")], "Dad2": [(1,"p2"),(1,"p4")],
          "Dabd": [(1,"p2"),(1,"p3"),(-1,"p1")], "Dx2b": [(1,"p4"),(1,"p3"),(-1,"p1")], "Dcb": [(1,"p3"),(-1,"p1")]}
def used(f):
    import re; b = open(f).read(); return {k: v for k, v in E_DENS.items() if re.search(rf"\b{k}\b", b)}
specs = [
 ("qgg3", "FQGG3", M4, {"Dac": [(1,"p2"),(1,"p3")], "Dad": [(1,"p2"),(1,"p4")], "Dbc": [(-1,"p1"),(1,"p3")],
                   "Dbd": [(-1,"p1"),(1,"p4")], "Dacd": [(1,"p2"),(1,"p3"),(1,"p4")],
                   "Dbcd": [(-1,"p1"),(1,"p3"),(1,"p4")], "Dcd": [(1,"p3"),(1,"p4")]},
  ["X1PV","X2PV","X1SY","X2SY"], ["      icd=1/(p3(4)*p4(4)-p3(1)*p4(1)-p3(2)*p4(2)-p3(3)*p4(3))"],
  "l q(p1) -> l q(p2) g(p3) g(p4): colour structures X1 = |A1|^2+|A2|^2,\nX2 = 2 Re A1 A2^*, helicity difference (PV) and sum (SY)"),
 ("d13", "FD13", M4, {"Dcd": [(1,"p3"),(1,"p4")], "Dx1": [(1,"p2"),(1,"p3"),(1,"p4")], "Dx2": [(-1,"p1"),(1,"p3"),(1,"p4")]},
  ["DPV","DSY"], None, "l q(p1) -> l q(p2) q'(p3) qbar'(p4), boson on the q line"),
 ("e3", "FE3", M4, None, ["EPV","ESY"], None, "identical-quark interference Re A_dir A_exch^*, all boson attachments;\nq(p1) -> q(p2) q(p3) qbar(p4)"),
 ("exx3", "FEXX3", M4, None, ["EXXPV","EXXSY"], None, "identical-quark interference, boson on the incoming-quark line in\nboth amplitudes (CC: pair flavour = partner of the incoming quark)"),
 ("exy3", "FEXY3", M4, None, ["EXYPV","EXYSY"], None, "interference of boson on the incoming line (g -> q3 qbar4) with\nboson on the (p2,p4) pair (line p1 -> p3); CC: q(p2), q'(p3), qbar'(p4)"),
 ("conthr3", "FCONTH3", ["k","p1","p2","p3","vv"], {"Dac": [(1,"p2"),(1,"p3")], "Dbc": [(-1,"p1"),(1,"p3")]},
  ["C3PV","C3SY"], None, "spin-correlated l q(p1) -> l q(p2) g(p3) with the gluon polarisation\nsum replaced by vv vv: helicity difference and sum"),
]
src = ["C Generated by derivations/o2/make_trees.py from FORM output (gen_o2.py,",
       "C gen_prod.py, wrap.py); do not edit by hand. Momenta in DISENT layout",
       "C (px,py,pz,E), physical (incoming quark p1, outgoing p2,p3,p4,",
       "C incoming lepton k). PV = same minus opposite lepton-quark helicity,",
       "C SY = sum (photon-like), in the normalisation of derivations/o2.", ""]
for name, sub, mom, dens, outs, extra, doc in specs:
    d = dens if dens is not None else used(f"prod/{name}.f")
    src.append(wrap.wrap(f"prod/{name}.f", sub, mom, d, outs, extra, doc))
out = sys.argv[1] if len(sys.argv) > 1 else "../../src/disent_o2_trees.f"
open(out, "w").write("\n".join(src))
print("wrote", out)
